name: Docker Image

env:
  IMAGE: ghcr.io/yiisoft-contrib/po4a
  TAG: 0.73

on:
  workflow_dispatch: ~
  workflow_run:
    workflows: [ "Checks" ]
    branches: [ "master" ]
    types:
      - completed

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-image-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "rfc3339=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
          push: ${{ github.ref == 'refs/heads/master' }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.rfc3339 }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
